#!/bin/sh

user="${USER}"
HOST="$(hostname)"
OS="$(uname -sr)"
DE="${XDG_CURRENT_DESKTOP}"
Shell="$(basename "$SHELL")"
CPU="$(sysctl -n hw.model)"
GPU="$(pciconf -lv | awk -F"'" '/vgapci/{getline; getline; print $2}')"
RAM="$(sysctl -n vm.stats.vm.v_page_count vm.stats.vm.v_free_count vm.stats.vm.v_inactive_count hw.pagesize | awk '
    NR==1 {total_pages=$1}
    NR==2 {free_pages=$1}
    NR==3 {inactive_pages=$1}
    NR==4 {
        page_bytes=$1;

        total_gb = (total_pages * page_bytes) / (1024^3);

        available_gb = ((free_pages + inactive_pages) * page_bytes) / (1024^3);
        used_gb = total_gb - available_gb;

        printf "%.1fG Used / %.0fG Total\n", used_gb, total_gb
    }
')"
Best_anime="Ganbare Nakamura-kun!!"
current_year="$(date +%Y)"

# COLORS
c1="\e[31m" # Red
c2="\e[32m" # Green
c3="\e[33m" # Yellow
c4="\e[34m" # Calm Blue
c5="\e[35m" # Violet
c6="\e[36m" # Arch Blue
c7="\e[37m" # White
c8="\e[90m" # Grey
c9="\e[91m" # Bright Red
c10="\e[92m" # Bright Green
c11="\e[93m" # Bright Yellow
c12="\e[94m" # Bright Blue
c13="\e[95m" # Bright Violet
c14="\e[96m" # Bright Arch Blue
c15="\e[97m" # Actual White
c20="\e[0m" # Normal
c21="\e[0;1m" # Bold

# An Error echo wrapper (prints to stderr and exits)
err0r() {
    # \033[1;31m = Bold Red, \033[0m = Reset
    printf '\033[1;31m[-] ERROR: %s\033[0m\n' "$*" >&2
    exit 86
}

# A Warning echo wrapper (prints to stderr)
warn() {
    # \033[1;33m = Bold Yellow, \033[0m = Reset
    printf '\033[1;33m[!] WARNING: %s\033[0m\n' "$*" >&2
}

# A Message echo wrapper (prints to stdout)
msg() {
    # \033[1;32m = Bold Green, \033[0m = Reset
    printf '\033[1;32m[+] %s\033[0m\n' "$*"
}

# The display

echo ""
echo -e "${c21}${user}@${HOST}${c20}"
echo
echo -e "${c1}     OS:${c20} ${OS}"
echo -e "${c3}     Desktop Environment:${c20} ${DE}"
echo -e "${c2}     Shell:${c20} ${Shell}"
echo -e "${c6}     CPU:${c20} ${CPU}"
echo -e "${c4}     GPU:${c20} ${GPU}"
echo -e "${c5}     RAM:${c20} ${RAM}"
echo -e "${c8}     The Best Anime:${c21} ${Best_anime}"
echo
echo
echo -e "${c20}     Simplinfo version 1.2         2026-${current_year}"
echo ""
