#!/bin/bash

# Software Info
if command -v lsb_release >/dev/null 2>&1; then
    DIS="$(lsb_release -sd)"
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    DIS="$PRETTY_NAME"
else
    DIS="Unknown Linux"
fi
if [ -n "$XDG_CURRENT_DESKTOP" ]; then
    DE="${XDG_CURRENT_DESKTOP}"
elif command -v wmctrl >/dev/null 2>&1; then
    DE="$(wmctrl -m | awk -F': ' ' /^Name/ {print $2}')"
else
    DE="Unknown DE or WM"
fi

# Hardware Info
DVI="$(printf "%s %s" "$(cat /sys/devices/virtual/dmi/id/sys_vendor)" "$(cat /sys/devices/virtual/dmi/id/product_name)")"

# Other Info
CURRENT_YEAR="$(date +%Y)"
UPTIME="$(uptime -p | sed 's/up //')"
if [ -s "$HOME/.bestanime" ]; then
    Best_anime="$(cat "$HOME/.bestanime")"
else
    Best_anime="Ganbare Nakamura-kun!!"
fi

# COLORS
c1="\e[31m" # Red
c2="\e[32m" # Green
c3="\e[33m" # Yellow
c5="\e[35m" # Violet
c6="\e[36m" # Arch Blue
c20="\e[0m" # Normal
c21="\e[0;1m" # Bold

# The display

echo ""
echo -e "${c1}     Distro:${c20} ${DIS}"
echo -e "${c3}     Uptime:${c20} ${UPTIME}"
echo -e "${c2}     Device:${c20} ${DVI}"
echo -e "${c6}     Desktop Environment:${c20} ${DE}"
echo -e "${c5}     The Best Anime:${c21} ${Best_anime}"
echo
echo
echo -e "${c20}     Simplinfo core LE version 2.1        2026-${CURRENT_YEAR}"
echo ""
