#!/bin/bash

# User and Host
user="${USER}"
HOST="$(hostname)"

# Software Info
if command -v lsb_release >/dev/null 2>&1; then
    DIS="$(lsb_release -sd)"
elif [ -f /etc/os-release ]; then
    . /etc/os-release
    DIS="$PRETTY_NAME"
else
    DIS="Unknown Linux"
fi
OS="$(uname -sr)"
DE="${XDG_CURRENT_DESKTOP}"
if [ -n "$XDG_CURRENT_DESKTOP" ]; then
    DE="$(XDG_CURRENT_DESKTOP)"
elif command -v wmctrl >/dev/null 2>&1; then
    DE="$(wmctrl -m | awk -F': ' ' /^Name/ {print $2}')"
else
    DE="Unknown DE or WM"
fi

# Hardware Info
DVI="$(printf "%s %s" "$(sudo dmidecode -s system-manufacturer)" "$(sudo dmidecode -s system-product-name)")"
if command -v lscpu >/dev/null 2>&1; then
    CPU="$(lscpu | grep 'Model name' | sed 's/.*: *//')"
elif command -v awk >/dev/null 2>&1; then
    CPU="$(awk -F': ' '/model name/ {print $2; exit}' /proc/cpuinfo)"
else 
    CPU="Unknown CPU"
fi
if command -v lspci >/dev/null 2>&1; then
    GPU="$(lspci | awk -F ': ' '/VGA|3D/ {print $2; exit}')"
elif command -v glxinfo >/dev/null 2>&1; then
    GPU="$(glxinfo -B | awk -F': ' '/Device:/ {print $2; exit}')"
else
    GPU="Unknown GPU"
fi
RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"

# Misc. Info
CURRENT_YEAR="$(date +%Y)"
UPTIME="$(uptime -p | sed 's/up //')"
if [ -s "$HOME/.bestanime" ]; then
    Best_anime="$(cat "$HOME/.bestanime")"
else
    Best_anime="Ganbare Nakamura-kun!!"
fi

# COLORS
c1="\e[31m" # Red
c2="\e[32m" # Green
c3="\e[33m" # Yellow
c4="\e[34m" # Calm Blue
c5="\e[35m" # Violet
c6="\e[36m" # Arch Blue
c7="\e[37m" # White
c8="\e[90m" # Grey
c9="\e[91m" # Bright Red
c10="\e[92m" # Bright Green
c11="\e[93m" # Bright Yellow
c12="\e[94m" # Bright Blue
c13="\e[95m" # Bright Violet
c14="\e[96m" # Bright Arch Blue
c15="\e[97m" # Actual White
c16="\e[38;5;208m" # Orange
c17="\e[38;5;219m" # Pink
c20="\e[0m" # Normal
c21="\e[0;1m" # Bold

# The display

echo ""
echo -e "${c21}${user}@${HOST}${c20}"
echo
echo -e "${c17}     Distro:${c20} ${DIS}"
echo -e "${c1}     Kernel:${c20} ${OS}"
echo -e "${c16}     Uptime:${c20} ${UPTIME}"
echo -e "${c11}     Desktop Environment:${c20} ${DE}"
echo -e "${c2}     Device:${c20} ${DVI}"
echo -e "${c6}     CPU:${c20} ${CPU}"
echo -e "${c4}     GPU:${c20} ${GPU}"
echo -e "${c5}     RAM:${c20} ${RAM}"
echo -e "${c8}     The Best Anime:${c21} ${Best_anime}"
echo
echo
echo -e "${c20}     Simplinfo LE version 2.0        2026-${CURRENT_YEAR}"
echo ""
